version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

  compile:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run compile

workflows:
  primary:
    jobs:
      - install
      - compile:
          requires:
            - install
          filters:
            branches:
              only:
                - main
