version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

  secrets:
    executor: node/default
    steps:
      - checkout
      - run: |
          # TODO: use CIRCLECI context to store secrets and pipe them into `.env` file
          echo "TESTING=SECRETS" >> .env
          echo "ETHERSCAN_API_KEY=$ETHERSCAN_API_KEY" >> .env
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .env
      - store_artifacts:
            path: .env

  compile:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      # get .env from secrets job.
      - attach_workspace:
          at: /home/circleci/project
      - run: npm run compile
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - artifacts
      - store_artifacts:
            path: artifacts

  # test:
  #   executor: node/default

  #   steps:
  #     - checkout
  #     - node/install-packages    
  #     # get .env from secrets job.
  #     - attach_workspace:
  #         at: /home/circleci/project
  #     # TODO: get coverage error fixed
  #     # - run: npm run cover
  #     - run: npm run test
  #     # - store_test_results:
  #     #     path: coverage

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      # get .env from secrets job.
      # get artifacts from compile job
      - attach_workspace:
          at: /home/circleci/project
      - run: |
          echo "deploying..."
          ls -la

workflows:
  primary:
    jobs:
      - install
      - secrets:
          context: web3
          requires:
            - install
      # - test:
      #     requires:
      #       - install
      - lint:
          requires:
            - install
      - compile:
          requires:
            - install
            - secrets
      - deploy:
          requires:
            - install
            - secrets
            # - test
            - lint
            - compile
          filters:
            branches:
              only:
                - main
