version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

workflows:
  primary:
    jobs:
      - install
