version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

  compile:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run compile
      - store_artifacts:
            path: artifacts

  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run cover

workflows:
  primary:
    jobs:
      - install
      - test:
          requires:
            - install
      - compile:
          requires:
            - install
      # - deploy:
      #     requires:
      #       - install
      #       - test
      #       - compile
      #     filters:
      #       branches:
      #         only:
      #           - main
